# Generated by Django 2.2.3 on 2019-07-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_typy',
            new_name='blog_type',
        ),
    ]
