# Generated by Django 2.2.3 on 2019-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190826_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
